# These are supported funding model platforms

# github: amirHossein-Ebrahimi
# patreon: # Replace with a single Patreon username
# ko_fi: # Replace with a single Ko-fi username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ['https://payping.ir/@amirhe']
