# These are supported funding model platforms

# github: amirHossein-Ebrahimi
# patreon: # Replace with a single Patreon username
# ko_fi: # Replace with a single Ko-fi username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
7
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
8
liberapay: # Replace with a single Liberapay username
9
issuehunt: # Replace with a single IssueHunt username
10
otechie: # Replace with a single Otechie username
11
